# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Upload AAB to Google Play Store"
  lane :upload_aab do
    upload_to_play_store(
      aab: "../android-builds/YoraaApp-release-signed.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Build and Upload AAB to Google Play Store"
  lane :build_and_upload do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Build signed release builds"
  lane :build_signed do
    gradle(task: "clean")
    gradle(task: "bundleRelease")
    gradle(task: "assembleRelease")
    
    # Copy signed builds to android-builds directory using Fastlane environment variables
    aab_path = Actions.lane_context[Actions::SharedValues::GRADLE_AAB_OUTPUT_PATH]
    apk_path = Actions.lane_context[Actions::SharedValues::GRADLE_APK_OUTPUT_PATH]
    
    sh "cp '#{aab_path}' ../android-builds/YoraaApp-release-signed.aab"
    sh "cp '#{apk_path}' ../android-builds/YoraaApp-release-signed.apk"
    
    UI.success "✅ Signed builds created:"
    UI.message "📱 AAB: android-builds/YoraaApp-release-signed.aab"
    UI.message "📱 APK: android-builds/YoraaApp-release-signed.apk"
  end
end
